version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: book-end-postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

volumes:
  postgres_data: