services:
  # Serviço do banco de dados PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: book-end-db
    restart: always
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Serviço da nossa API Node.js/Express
  app:
    container_name: book-end-app
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres-data: